App fix
crowdproj/crowdproj-ratings pull request #5
Opened 2023-04-10 07:27 UTC by shvetson

Сергей, добрый день!
Внес исправления по Вашим замечаниям.
Извините, что задержался с обратной связью, немного приболел.
Сейчас все наверстаю.

2023-04-13 18:47 UTC, svok requested changes
Олег, сделайте еще небольшие правки. В целом, практически готово

2023-04-13 18:47 UTC, svok commented on mappers-v1/src/main/kotlin/MapperV1ToTransport.kt
> +import kotlinx.datetime.toLocalDateTime
Эти два импорта не используются

2023-04-13 18:47 UTC, svok commented on testing/src/jvmMain/kotlin/domain/RatingObj.kt
> +class RatingObj(
Зачем это все?
Просто объявите его data class и не понадобится переопределять все эти методы

2023-04-13 18:47 UTC, svok commented on testing/src/jvmMain/kotlin/domain/RatingScore.kt
> +class RatingScore(
```suggestion
data class RatingScore(
```

2023-04-13 18:47 UTC, svok commented on testing/src/jvmTest/kotlin/MyTddTest.kt
> +    @DisplayName("\uD83D\uDC4D")
Зачем еще DisplayName? Вы же уже имя читаемое задали

2023-04-13 18:47 UTC, svok commented on README.md
> +**A microservice for managing ratings (user, article, product, etc) on marketplace.**
Синхронизируйтесь  с веткой 
![image](https://user-images.githubusercontent.com/12605904/231854324-941ba9de-0ab8-4b93-892c-977f09163f73.png)

Каждый раз присылаете ПР в main, я его каждый раз переставляю на эту ветку, а ваши ПР растут из-за отсутствия синхронизации с ней

2023-04-14 13:09 UTC, shvetson commented on mappers-v1/src/main/kotlin/MapperV1ToTransport.kt
> +import kotlinx.datetime.toLocalDateTime
удалил

2023-04-14 13:09 UTC, shvetson commented on testing/src/jvmMain/kotlin/domain/RatingObj.kt
> +class RatingObj(
исправил

2023-04-14 13:10 UTC, shvetson commented on testing/src/jvmMain/kotlin/domain/RatingScore.kt
> +class RatingScore(
исправил

2023-04-14 13:10 UTC, shvetson commented on testing/src/jvmTest/kotlin/MyTddTest.kt
> +    @DisplayName("\uD83D\uDC4D")
изменил

2023-04-14 13:11 UTC, shvetson commented
Внес исправления

2023-04-14 14:29 UTC, shvetson commented on README.md
> +**A microservice for managing ratings (user, article, product, etc) on marketplace.**
ок

2023-04-15 19:20 UTC, merged

2023-04-15 19:21 UTC, svok reviewed
Принято